import Sundogcert.Basic
import Sundogcert.Certificate
import Sundogcert.Instance
import Sundogcert.Scaling
import Sundogcert.Looseness
import Sundogcert.CertWall
import Sundogcert.Degradation
import Sundogcert.CheckCost
import Sundogcert.ShadowDecay
import Sundogcert.ShadowDecayGeneral
import Sundogcert.ShadowDecayCauchy
import Sundogcert.HaloGeometry
import Sundogcert.FaradayAB
import Sundogcert.SortingCert
import Sundogcert.RSCertificate
import Sundogcert.DecodingNPHard
import Sundogcert.AxiomAudit
import Sundogcert.ShadowDecayLattice
-- The 3SAT ≤ 3DM ≤ X3C ≤ Decodes Karp reduction (machine-checked correctness).
import Sundogcert.MatchingNPHard
import Sundogcert.SATNPHard
import Sundogcert.VarWheel
import Sundogcert.ClauseGadget
import Sundogcert.SATReduction
import Sundogcert.ThreeDMReindex
import Sundogcert.SATReductionIncidence
import Sundogcert.SATReductionReverse
import Sundogcert.SATReductionForward
import Sundogcert.SATReductionMain
