/-
# OrderRelative — the n-ary grading law and the structure-theorem mode-vector

`orderOf_prod_eq_lcm` (`OrderRelativeGrading`) is binary (`M × N`). This module takes it to arbitrary
finite products and cashes out the deferred **structure-theorem** form of the mode-vector.

- **The n-ary law** (`orderOf_pi_eq_lcm`, additive twin `addOrderOf_pi_eq_lcm`): for a finite family
  of monoids, `orderOf (x : ∀ i, M i) = Finset.univ.lcm (fun i => orderOf (x i))`. Not in mathlib —
  it has only `orderOf_piMulSingle` (one nontrivial coordinate).
- **The structure theorem** (`structure_order`): for a finite abelian group in invariant-factor form
  `∀ i, ZMod (dᵢ)`, the additive order of the diagonal `(1,…,1)` is `Finset.univ.lcm d` — the join of
  the invariant factors. This is exactly the deferred "scalar = join of the invariant-factor vector."
- **The mode-vector** (`structure_mode_vector`): scalar order `= lcm d` (the join) while the per-axis
  orders are the vector `d` — the scalar is the lossy join of a latent vector, in full generality.

The `ℕ`-`orderOf` convention (`0` = infinite order) makes this *unify* the earlier binary free/torsion
`mixed_mode_vector`: a coordinate with `dᵢ = 0` is `ZMod 0 = ℤ` (a **free** summand, `addOrderOf 1 =
0`), and `Finset.lcm` absorbs `0`, so any free coordinate sends the scalar to `0` (= `⊤`, "free part
dominates"). Torsion and free coordinates live in one formula.
-/
import Sundogcert.OrderRelativeGrading
import Mathlib.Algebra.GCDMonoid.Finset

namespace Sundog.OrderRelative.Structure

variable {ι : Type*} [Fintype ι]

/-- **The n-ary grading law.** For a finite family of monoids, the order of a tuple in the product is
the `lcm` of the coordinate orders — generalizing `orderOf_prod_eq_lcm` from `M × N` to `∀ i, M i`.
The additive twin `addOrderOf_pi_eq_lcm` is generated by `@[to_additive]`. -/
@[to_additive addOrderOf_pi_eq_lcm "The n-ary grading law, additively: the additive order of a tuple
is the `lcm` of the coordinate additive orders."]
theorem orderOf_pi_eq_lcm {M : ι → Type*} [∀ i, Monoid (M i)] (x : ∀ i, M i) :
    orderOf x = Finset.univ.lcm (fun i => orderOf (x i)) := by
  apply Nat.dvd_antisymm
  · apply orderOf_dvd_of_pow_eq_one
    funext i
    rw [Pi.pow_apply, Pi.one_apply]
    exact orderOf_dvd_iff_pow_eq_one.mp (Finset.dvd_lcm (Finset.mem_univ i))
  · apply Finset.lcm_dvd
    intro i _
    apply orderOf_dvd_of_pow_eq_one
    have h := congrFun (pow_orderOf_eq_one x) i
    rwa [Pi.pow_apply, Pi.one_apply] at h

/-- **The structure theorem.** For a finite abelian group in invariant-factor form `∀ i, ZMod (dᵢ)`,
the additive order of the diagonal `(1,…,1)` is the `lcm` of the invariant factors — the join of the
factor vector. (A `dᵢ = 0` coordinate is the free summand `ℤ`, and `lcm` absorbs its `0`.) -/
theorem structure_order (d : ι → ℕ) :
    addOrderOf (fun i => (1 : ZMod (d i))) = Finset.univ.lcm d := by
  rw [addOrderOf_pi_eq_lcm]
  simp only [ZMod.addOrderOf_one]

/-- **The structure-theorem mode-vector.** On one object `(1,…,1) ∈ ∀ i, ZMod (dᵢ)`: the SCALAR
additive order is the join `lcm d`, while the per-axis orders are the VECTOR `d`. The scalar is the
lossy join of the latent invariant-factor vector — the general form the cohomological
`mixed_mode_vector` was a two-coordinate instance of. -/
theorem structure_mode_vector (d : ι → ℕ) :
    addOrderOf (fun i => (1 : ZMod (d i))) = Finset.univ.lcm d
      ∧ ∀ i, addOrderOf ((fun j => (1 : ZMod (d j))) i) = d i :=
  ⟨structure_order d, fun i => ZMod.addOrderOf_one (d i)⟩

end Sundog.OrderRelative.Structure
