/-
# OrderRelative — the grading law, abstracted (group-order axes as instances of one lemma)

The composition-law slate proved "scalar order = join" **axis by axis** (cohomological, radical) and
stated the general principle only in prose: *`ord` is a join-homomorphism to the divisibility
lattice — it carries the cancellation-free coproduct to the `lcm`.* This module promotes that to one
machine-checked lemma and recovers the axes as instances.

**The abstract law** (`orderOf_prod_eq_lcm`, with its additive twin via `@[to_additive]`): for ANY
two monoids and any `x : M`, `y : N`,

> `orderOf ((x, y) : M × N) = Nat.lcm (orderOf x) (orderOf y)`.

It is the *order-level* consequence of the lane's pointwise coproduct law
(`coproduct_pow_eq_one : (x,y)^j = 1 ↔ x^j = 1 ∧ y^j = 1`): the annihilator set of the pair is the
intersection of the two annihilator ideals `(orderOf x)` and `(orderOf y)`, whose generator is the
`lcm`. `Nat.lcm` is the join in the divisibility lattice on `ℕ` — the order distinct from `≤` that
the slate flagged. So `orderOf` is literally a join-homomorphism `(M × N, ⊗) → (ℕ, lcm)`.

**The boundary, made precise by the abstraction's domain.** This law is exactly why the *group-order*
axes (cohomological = additive order in `ZMod`/`ℤ`; radical = multiplicative order of `[x]` in
`ℝˣ/ℚˣ`) hold the composition law, and why the others cannot be instances of it: algebraic-degree and
search-reach have NO monoid on their targets with `ord = orderOf` (the cancelling product is the
within-group `·`, not the coproduct), and the moment axis is the degenerate `{1, ⊤}`-semilattice
(idempotent) case. The abstraction's reach carves the 3-positive / 2-negative split.
-/
import Sundogcert.OrderRelativeConverse
import Mathlib.Data.ZMod.Basic

namespace Sundog.OrderRelative.Grading

open Sundog.OrderRelative.Converse

/-- **The abstract grading law.** For any two monoids, the order of a pair in the product (the
cancellation-free coproduct) is the `lcm` of the two orders — the divisibility-join. Proved from the
lane's pointwise coproduct law `coproduct_pow_eq_one`; the additive twin `addOrderOf_prod_eq_lcm` is
generated by `@[to_additive]`. -/
@[to_additive addOrderOf_prod_eq_lcm "The abstract grading law, additively: the additive order of a
pair in the product is the `lcm` of the two additive orders."]
theorem orderOf_prod_eq_lcm {M N : Type*} [Monoid M] [Monoid N] (x : M) (y : N) :
    orderOf ((x, y) : M × N) = Nat.lcm (orderOf x) (orderOf y) := by
  apply Nat.dvd_antisymm
  · -- `orderOf (x,y) ∣ lcm`: the pair is annihilated by the lcm (both coordinates are).
    apply orderOf_dvd_of_pow_eq_one
    rw [coproduct_pow_eq_one]
    exact ⟨orderOf_dvd_iff_pow_eq_one.mp (Nat.dvd_lcm_left _ _),
           orderOf_dvd_iff_pow_eq_one.mp (Nat.dvd_lcm_right _ _)⟩
  · -- `lcm ∣ orderOf (x,y)`: each coordinate's order divides the pair's (read off `pow_orderOf`).
    have h := (coproduct_pow_eq_one x y (orderOf ((x, y) : M × N))).mp (pow_orderOf_eq_one _)
    exact Nat.lcm_dvd (orderOf_dvd_of_pow_eq_one h.1) (orderOf_dvd_of_pow_eq_one h.2)

/-- **Cohomological axis as an instance.** The composite additive order of `(1, 1) : ZMod a × ZMod b`
is `lcm a b` — the lane's `compose_order_eq_lcm` now drops out of the abstract law together with
`ZMod.addOrderOf_one`, with no bespoke `ZMod` computation. -/
theorem cohomological_compose (a b : ℕ) :
    addOrderOf ((1, 1) : ZMod a × ZMod b) = Nat.lcm a b := by
  rw [addOrderOf_prod_eq_lcm, ZMod.addOrderOf_one, ZMod.addOrderOf_one]

end Sundog.OrderRelative.Grading
